// <auto-generated />
using System;
using MejorPrecio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MejorPrecio.Data.Migrations
{
    [DbContext(typeof(MejorPrecioContext))]
    [Migration("20260715180855_InitialCreatePrecio")]
    partial class InitialCreatePrecio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MejorPrecio.Data.Entities.Categoria", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Presentar")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.HasKey("Codigo");

                    b.ToTable("Categoria", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductoProveed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateOnly>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("ProductoProveed")
                        .HasDatabaseName("IX_Precio_ProductoProveed");

                    b.HasIndex("Proveedor", "ProductoProveed");

                    b.HasIndex("VigenciaDesde", "VigenciaHasta", "Categoria")
                        .HasDatabaseName("IX_Precio_Vigencia_Categoria");

                    b.ToTable("Precio", (string)null);
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.ProductoProveedor", b =>
                {
                    b.Property<string>("Proveedor")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ProductoProveed")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnidadProveed")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Proveedor", "ProductoProveed");

                    b.ToTable("ProductoProveedor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.Proveedor", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Proveedor");

                    b.Property<string>("CUIT")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Domicilio")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EstadoId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("ImporteMinOC")
                        .HasColumnType("numeric(18,0)");

                    b.Property<string>("Localidad")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ModalidadPed")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Pais")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("Codigo");

                    b.ToTable("Proveedor", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.Precio", b =>
                {
                    b.HasOne("MejorPrecio.Data.Entities.Categoria", "CategoriaNavigation")
                        .WithMany("Precios")
                        .HasForeignKey("Categoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MejorPrecio.Data.Entities.Proveedor", "ProveedorNavigation")
                        .WithMany("Precios")
                        .HasForeignKey("Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MejorPrecio.Data.Entities.ProductoProveedor", "ProductoProveedorNavigation")
                        .WithMany("Precios")
                        .HasForeignKey("Proveedor", "ProductoProveed")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaNavigation");

                    b.Navigation("ProductoProveedorNavigation");

                    b.Navigation("ProveedorNavigation");
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.ProductoProveedor", b =>
                {
                    b.HasOne("MejorPrecio.Data.Entities.Proveedor", "ProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("Proveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProveedorNavigation");
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.Categoria", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.ProductoProveedor", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("MejorPrecio.Data.Entities.Proveedor", b =>
                {
                    b.Navigation("Precios");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
